version: '3.1'
services:
  # API service
  ollama:
    image: registry.cn-hangzhou.aliyuncs.com/docker_all_mirrors/ollama:latest
    container_name: ollama
    restart: always
    volumes:
        # Mount the storage directory to the container, for storing user files.
        - ./models:/root/.ollama
    # uncomment to expose aidex-api port to host
    ports:
      - "11434:11434"
    networks:
      - ollama_network


networks:
  ollama_network:
    driver: bridge

