version: '3.8'

services:
  # ######################################### GPU 部署 #########################################
  # xinference:
  #   image: xprobe/xinference:v0.15.3
  #   container_name: xinference-gpu
  #   restart: always
  #   ports:
  #     - "9998:9997"
  #   environment:
  #     - XINFERENCE_HOME=/opt/xinference
  #     - XINFERENCE_MODEL_SRC=modelscope
  #     - XINFERENCE_MODEL_SRC=hf-mirror  # 指定从 Hugging Face 镜像站下载
  #   volumes:
  #     - /opt/xinference_gpu:/opt/xinference
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
  #   command: xinference-local -H 0.0.0.0
  

  ######################################### CPU 部署 #########################################
  xinference:
    image: docker-registry.neuedu.com/xprobe/xinference:v0.15.2-cpu
    container_name: xinference-cpu
    restart: always
    ports:
      - "11007:9997"
    environment:
      - XINFERENCE_HOME=/opt/xinference
      - XINFERENCE_MODEL_SRC=hf-mirror  # 指定从 Hugging Face 镜像站下载
    volumes:
      - /opt/xinference:/opt/xinference
    command: xinference-local -H 0.0.0.0