version: '3.8'
services:
  vllm:
    image: vllm/vllm:latest # 使用官方或构建的 vLLM 镜像
    container_name: vllm-service
    restart: always
    ports:
      - "8000:8000"  # 映射服务端口，修改为实际需要的端口
    volumes:
      - ./models:/models  # 模型存储路径
    environment:
      - VLLM_MODEL_NAME=gpt-3.5-turbo  # 指定模型名称，例如 GPT 系列
      - VLLM_MODEL_PATH=/models/gpt-3.5-turbo  # 模型路径
    # command: >
    #   vllm-serve --model-name=${VLLM_MODEL_NAME} 
    #              --model-path=${VLLM_MODEL_PATH} 
    #              --port=8000
    command: >
      vllm-serve