version: '3.8'

services:
  ollama:
    build:
      context: .                 # Dockerfile 的路径
    container_name: ollama       # 容器名称
    restart: always              # 自动重启
    ports:
      - "11434:11434"            # 映射端口
    volumes:
      - ./models:/root/.ollama     # 持久化模型数据存储
    environment:
      # 可选：允许传递模型版本或其他配置
      MODEL_NAME: "qwen2:0.5b"
