version: '3.8'

services:
  ollama:
    build:
      context: .
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    environment:
      MODEL_REPO: "https://hf-mirror.com/google/gemma-2-2b" # Replace with your model repository
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge