version: '3.8'  # 你可以根据需要使用不同的版本

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./models:/root/.ollama
    ports:
      # ollama服务默认端口是11434， 这里向外暴露端口是11411
      - "11411:11434"
    restart: always