version: '3.8'

services:
  ollama:
    build:
      context: .
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"  # 曝露 Ollama API 服务端口
    environment:
      MODEL_NAME: "Qwen2.5-1.5B-Instruct"       # 模型名称
      MODEL_REPO: "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct" # 模型仓库地址
    volumes:
      - ./models:/root/.ollama # 挂载模型目录
    networks:
      - ollama_network

networks:
  ollama_network:
    driver: bridge