version: '3.8'

services:
  ollama:
    build:
      context: .
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama
    environment:
      MODEL_NAME: "qwen2:0.5b"
